import { useEffect, useState } from 'react';
import { Icon, Brand, FieldArt, Badge, Button, Modal } from './ui';
import { portals, useWorkspace } from './workspace';
import { Dashboard, Scan, Risk, Fields, Hub, MapView, Reviews, Directory, Welfare, Anomaly, Retraining, Relief } from './screens';

function initialRole() { try { return sessionStorage.getItem('agri-role') || ''; } catch { return ''; } }
function initialPage() { return window.location.hash.slice(1) || 'overview'; }
export default function MainApp() {
  const [role, setRole] = useState(initialRole), [page, setPage] = useState(initialPage);
  const [menu, setMenu] = useState(false), [login, setLogin] = useState(''), [error, setError] = useState('');
  const [toast, setToast] = useState(''), [language, setLanguage] = useState('en'), [help, setHelp] = useState(false);
  const { data, update, storageError } = useWorkspace();
  const portal = portals[role], notify = message => setToast(message);
  useEffect(() => { const change = () => { setPage(initialPage()); setMenu(false); }; window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 6000); return () => clearTimeout(id); }, [toast]);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const navigate = target => { window.location.assign(`#${target}`); setPage(target); setMenu(false); window.scrollTo({ top: 0, behavior: 'instant' }); };
  const enter = event => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    if (form.get('username').trim() !== login || form.get('password') !== '123') { setError('Use the demo credentials shown below to enter this workspace.'); return; }
    setRole(login); try { sessionStorage.setItem('agri-role', login); } catch { /* Session remains usable in memory. */ }
    navigate('overview'); setLogin(''); setError('');
  };
  const logout = () => { setRole(''); if ('speechSynthesis' in window) speechSynthesis.cancel(); try { sessionStorage.removeItem('agri-role'); } catch { /* No persistent session. */ } navigate('overview'); };
  const readPage = () => {
    if (!('speechSynthesis' in window)) { notify('Read aloud is not supported by this browser.'); return; }
    if (speechSynthesis.speaking) { speechSynthesis.cancel(); notify('Reading stopped.'); return; }
    const speech = new SpeechSynthesisUtterance(document.querySelector('main')?.innerText || ''); speech.lang = 'en-IN'; speech.onerror = () => notify('Audio could not start. Check your browser sound settings.'); speechSynthesis.speak(speech); notify('Reading this page aloud. Select Read aloud again to stop.');
  };
  if (!portal) return <div className="welcome"><header className="welcome-header"><Brand /><Badge>AGRICULTURAL INTELLIGENCE</Badge></header><main className="welcome-grid">
    <section className="welcome-story"><div className="eyebrow"><span className="status-dot" /> ROOTED IN KNOWLEDGE. GROWN TOGETHER.</div><h1>Healthier crops.<br />Stronger <em>communities.</em></h1><p>A connected workspace for the people who grow, protect, and care for our land.</p><FieldArt /><div className="story-bottom"><span><Icon name="shield" /> From field to district</span><span>One connected ecosystem</span></div></section>
    <section className="welcome-access"><div className="eyebrow">YOUR WORK STARTS HERE</div><h2>Choose your workspace</h2><p className="muted">The right tools, for your role in the field.</p><div className="portal-list">{Object.entries(portals).map(([id, item]) => <button key={id} className="portal-choice" onClick={() => { setLogin(id); setError(''); }}><span className={`icon-box ${id}`}><Icon name={item.icon} /></span><span><strong>{item.name}</strong><small>{item.description}</small></span><Icon name="arrow" /></button>)}</div><div className="demo-notice"><Icon name="info" /><p><strong>Explore the demonstration</strong><br />Sample farm data and local workflows. No real alerts, diagnoses, or payments are issued.</p></div><div className="access-footer"><Icon name="leaf" /> Built for better growing decisions.</div></section>
    </main><footer className="welcome-footer"><span>Agri-Vyakaroti · Cultivating confidence</span><span>Jalgaon, Maharashtra</span></footer>
    {login && <Modal title={`${portals[login].name} access`} onClose={() => setLogin('')}><p className="muted">Sign in to the demonstration workspace.</p><form onSubmit={enter} className="form-stack"><label htmlFor="username">Username<input id="username" name="username" autoComplete="username" defaultValue={login} required /></label><label htmlFor="password">Password<input id="password" name="password" type="password" autoComplete="current-password" required /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="hint">Demo credentials: <strong>{login}</strong> / <strong>123</strong></div><Button type="submit" icon="arrow">Enter workspace</Button></form></Modal>}</div>;
  const allowed = ['overview', ...portal.nav.map(n => n.id)], activePage = allowed.includes(page) ? page : 'overview';
  const navItems = [{ id: 'overview', label: 'Overview', mr: 'आढावा', icon: 'grid' }, ...portal.nav], current = navItems.find(n => n.id === activePage);
  const props = { data, update, notify, navigate, role };
  const screens = { overview: Dashboard, scan: Scan, risk: Risk, fields: Fields, hub: Hub, map: MapView, reviews: Reviews, directory: Directory, welfare: Welfare, anomaly: Anomaly, retraining: Retraining, outbreak: MapView, relief: Relief }, Screen = screens[activePage];
  return <div className={`app-shell role-${role}`}><a href="#main-content" className="skip-link">Skip to content</a>{menu && <button className="nav-scrim" aria-label="Close navigation" onClick={() => setMenu(false)} />}
    <aside className={`sidebar ${menu ? 'is-open' : ''}`}><Brand /><div className="workspace-label">{portal.name} workspace</div><nav aria-label="Main navigation">{navItems.map(item => <button key={item.id} className={`nav-item ${activePage === item.id ? 'active' : ''}`} aria-current={activePage === item.id ? 'page' : undefined} onClick={() => navigate(item.id)}><Icon name={item.icon} /><span>{language === 'mr' ? item.mr || item.label : item.label}</span>{item.id === 'reviews' && <span className="nav-count">{data.cases.filter(c => c.status === 'pending').length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><Icon name="sprout" /><strong>A little guidance goes a long way.</strong><p>Find your way around the workspace.</p><button onClick={() => setHelp(true)}>Quick guide <Icon name="arrow" /></button></div><button className="profile" onClick={logout} title="Sign out"><span className="avatar">{portal.initials}</span><span><strong>{portal.user}</strong><small>{portal.name} · Sign out</small></span><Icon name="logout" /></button></div></aside>
    <div className="workspace-main"><header className="topbar"><div className="topbar-context"><button className="icon-button mobile-menu" aria-label="Open navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}><Icon name="menu" /></button><span className="breadcrumb">Workspace <Icon name="chevron" /> <strong>{current.label}</strong></span></div><div className="topbar-actions"><span className="demo-pill"><span className="status-dot" /> Demo workspace</span><button className="icon-button" onClick={readPage} aria-label="Read aloud" title="Read aloud"><Icon name="volume" /></button><button className="language-button" onClick={() => { setLanguage(language === 'en' ? 'mr' : 'en'); notify(language === 'en' ? 'Navigation is now in Marathi. Detailed content is currently available in English.' : 'Navigation is now in English.'); }} aria-label="Change navigation language"><Icon name="globe" />{language === 'en' ? 'EN' : 'मराठी'}</button><span className="avatar small">{portal.initials}</span></div></header>
      <main id="main-content" className="page-content" key={`${role}-${activePage}`} tabIndex={-1} lang="en">{storageError && <div className="notice warning" role="alert">Changes are available for this session only. Browser storage is unavailable or full.</div>}<Screen {...props} /></main><footer className="app-footer"><span><Icon name="leaf" /> Growing better, together.</span><span>Sample data · Saved on this device</span></footer></div>
    {toast && <div className="toast" role="status"><Icon name="check" /><span>{toast}</span><button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast('')}><Icon name="close" /></button></div>}{help && <Modal title="Your workspace, at a glance" onClose={() => setHelp(false)}><div className="form-stack"><p>Use the navigation to explore your tools. Fields, reports, reviews, and drafts are saved in this browser and shared between demo roles on this device.</p><p>Crop scans and weather forecasts are demonstrations. Broadcasts, retraining, and relief actions create local drafts or simulations; they do not contact external services.</p><p>Use Read aloud in the top bar for spoken content. The language control translates navigation labels.</p><Button onClick={() => setHelp(false)}>Got it</Button></div></Modal>}</div>;
}
